services:
  fankarr:
    image: masutayunikon/fankarr:3.25.0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - GITHUB_RAW_URL=${GITHUB_RAW_URL}
    dns:
      - ${DNS_IP}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data:/app/data
      - ${ROOT_FOLDER_HOST}/media:/media
    restart: unless-stopped
    x-runtipi:
      is_main: true
      internal_port: 9898
x-runtipi:
  schema_version: 2