version: '3.8'

services:
  nuxtapp:
    image: masutayunikon/nuxt-portfolio:latest
    build:
      context: .
      args:
        GIT_REPO: ${GIT_REPO}
        APP_DATA_DIR: ${APP_DATA_DIR}
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${APP_PORT}
    volumes:
      - ${APP_DATA_DIR}
    restart: unless-stopped
    networks:
      - tipi_main_network
