version: '3.8'

services:
  nuxtapp:
    image: masutayunikon/nuxt-portfolio:latest
    build:
      context: .
      args:
        GIT_REPO: ${GIT_REPO}
        STATE_SECRET: ${STATE_SECRET}
        SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
        SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
        SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
        GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
        GITHUB_REDIRECT_URI: ${GITHUB_REDIRECT_URI}
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${APP_PORT}
