version: '3.8'

services:
  yunikon:
    image: masutayunikon/yunikon:latest
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ${APP_DATA_DIR}
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.nuxt-portfolio-web-redirect.redirectscheme.scheme: https
      traefik.http.services.nuxt-portfolio.loadbalancer.server.port: ${APP_PORT}
      # Web
      traefik.http.routers.nuxt-portfolio-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.nuxt-portfolio-insecure.entrypoints: web
      traefik.http.routers.nuxt-portfolio-insecure.service: yunikon
      traefik.http.routers.nuxt-portfolio-insecure.middlewares: yunikon-web-redirect
      # Websecure
      traefik.http.routers.nuxt-portfolio.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.nuxt-portfolio.entrypoints: websecure
      traefik.http.routers.nuxt-portfolio.service: yunikon
      traefik.http.routers.nuxt-portfolio.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.nuxt-portfolio-local-insecure.rule: Host(`insecure.${LOCAL_DOMAIN}`)
      traefik.http.routers.nuxt-portfolio-local-insecure.entrypoints: web
      traefik.http.routers.nuxt-portfolio-local-insecure.service: yunikon
      traefik.http.routers.nuxt-portfolio-local-insecure.middlewares: yunikon-web-redirect
      # Local domain secure
      traefik.http.routers.nuxt-portfolio-local.rule: Host(`local.${LOCAL_DOMAIN}`)
      traefik.http.routers.nuxt-portfolio-local.entrypoints: websecure
      traefik.http.routers.nuxt-portfolio-local.service: yunikon
      traefik.http.routers.nuxt-portfolio-local.tls: true
