version: '3.8'

services:
  yunikon:
    image: masutayunikon/yunikon:latest
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ${APP_DATA_DIR}
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels: # Use your editors search and replace feature to replace all instances of "myapp" with your app name in the traefik labels
      # Main
      traefik.enable: true
      traefik.http.middlewares.myapp-web-redirect.redirectscheme.scheme: https
      traefik.http.services.myapp.loadbalancer.server.port: 3000 # Should be the same as the app internal port so for this example 9443
      # Web
      traefik.http.routers.myapp-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.myapp-insecure.entrypoints: web
      traefik.http.routers.myapp-insecure.service: yunikon
      traefik.http.routers.myapp-insecure.middlewares: yunikon-web-redirect
      # Websecure
      traefik.http.routers.myapp.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.myapp.entrypoints: websecure
      traefik.http.routers.myapp.service: yunikon
      traefik.http.routers.myapp.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.myapp-local-insecure.rule: Host(`yunikon.${LOCAL_DOMAIN}`)
      traefik.http.routers.myapp-local-insecure.entrypoints: web
      traefik.http.routers.myapp-local-insecure.service: yunikon
      traefik.http.routers.myapp-local-insecure.middlewares: yunikon-web-redirect
      # Local domain secure
      traefik.http.routers.myapp-local.rule: Host(`yunikon.${LOCAL_DOMAIN}`)
      traefik.http.routers.myapp-local.entrypoints: websecure
      traefik.http.routers.myapp-local.service: yunikon
      traefik.http.routers.myapp-local.tls: true
