services:
  pygege:
    image: masutayunikon/pygege:latest
    container_name: pygege
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    ports:
      - ${APP_PORT}:8000
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
    restart: unless-stopped

    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.pygege-web-redirect.redirectscheme.scheme: https
      traefik.http.services.pygege.loadbalancer.server.port: 5690
      # Web
      traefik.http.routers.pygege-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.pygege-insecure.entrypoints: web
      traefik.http.routers.pygege-insecure.service: pygege
      traefik.http.routers.pygege-insecure.middlewares: pygege-web-redirect
      # Websecure
      traefik.http.routers.pygege.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.pygege.entrypoints: websecure
      traefik.http.routers.pygege.service: pygege
      traefik.http.routers.pygege.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.pygege-local-insecure.rule: Host(`pygege.${LOCAL_DOMAIN}`)
      traefik.http.routers.pygege-local-insecure.entrypoints: web
      traefik.http.routers.pygege-local-insecure.service: pygege
      traefik.http.routers.pygege-local-insecure.middlewares: pygege-web-redirect
      # Local domain secure
      traefik.http.routers.pygege-local.rule: Host(`pygege.${LOCAL_DOMAIN}`)
      traefik.http.routers.pygege-local.entrypoints: websecure
      traefik.http.routers.pygege-local.service: pygege
      traefik.http.routers.pygege-local.tls: true
      runtipi.managed: true