services:
  portfolio:
    image: masutayunikon/portfolio:v1.0.1
    container_name: portfolio
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: 3000

      NUXT_SMTP_HOST: ${NUXT_SMTP_HOST}
      NUXT_SMTP_PORT: ${NUXT_SMTP_PORT}
      NUXT_SMTP_USER: ${NUXT_SMTP_USER}
      NUXT_SMTP_PASS: ${NUXT_SMTP_PASS}
      NUXT_SMTP_TO_EMAIL: ${NUXT_SMTP_TO_EMAIL}
      NUXT_FROM_EMAIL: ${NUXT_FROM_EMAIL}

    ports:
      - "${APP_PORT}:3000"


